package com.meet.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.*;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Meeting {

    /**
     * Unique identifier for the Meeting entity.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer meetingId;

    /**
     * Unique identifier for the host of the meeting.
     */
    private Integer hostId;

    /**
     * Number of rooms required for the meeting.
     */
    private Integer noOfRooms;

    /**
     * Title or heading of the meeting.
     */
    private String meetingHeading;

    /**
     * Start time of the meeting.
     */
    private LocalDateTime fromTime;

    /**
     * End time of the meeting.
     */
    private LocalDateTime toTime;

    /**
     * Date of the meeting.
     */
    private LocalDate date;

    /**
     * Time of the meeting.
     */
    private LocalTime time;

    /**
     * Duration of the meeting in minutes.
     */
    private Long period;

    /**
     * List of IDs representing the people included in the meeting.
     */
    private List<Integer> peopleIncluded;

    /**
     * Constructs a new Meeting object as a copy of the given Meeting object.
     * @param meeting The Meeting object to copy.
     */
    public Meeting(Meeting meeting) {
        super();
        this.meetingId = meeting.getMeetingId();
        this.hostId = meeting.getHostId();
        this.noOfRooms = meeting.getNoOfRooms();
        this.meetingHeading = meeting.getMeetingHeading();
        this.fromTime = meeting.getFromTime();
        this.toTime = meeting.getToTime();
        this.date = meeting.getDate();
        this.time = meeting.getTime();
        this.period = meeting.getPeriod();
        this.peopleIncluded = meeting.getPeopleIncluded();
    }
}
